---
#
# Copyright 2016 VVL Systems & Consulting
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# Section 2.1 inetd Services
#
- name: 2.1.1 Ensure chargen services are not enabled (check if exists) (Scored)
  stat: path=/etc/xinetd.d/chargen-dgram
  register: chargen_dgram
  tags:
    - scored
    - section2.1
    - section2.1.1

- name: 2.1.1 Ensure chargen services are not enabled (Disable service) (Scored)
  service: >
      name=chargen-dgram
      state=stopped
      enabled=no
  when: chargen_dgram.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.1

- name: 2.1.1 Ensure chargen services are not enabled (check if exists) (Scored)
  stat: path=/etc/xinetd.d/chargen-stream
  register: chargen_stream
  tags:
    - scored
    - section2.1
    - section2.1.1

- name: 2.1.1 Ensure chargen services are not enabled (Disable service) (Scored)
  service: >
      name=chargen-stream
      state=stopped
      enabled=no
  when: chargen_stream.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.1

- name: 2.1.2 Ensure daytime services are not enabled (check if exists) (Scored)
  stat: path=/etc/xinetd.d/daytime-dgram
  register: daytime_dgram
  tags:
    - scored
    - section2.1
    - section2.1.2

- name: 2.1.2 Ensure daytime services are not enabled (Disable service) (Scored)
  service: >
      name=daytime-dgram
      state=stopped
      enabled=no
  when: daytime_dgram.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.2

- name: 2.1.2 Ensure daytime services are not enabled (check if exists) (Scored)
  stat: path=/etc/xinetd.d/daytime-stream
  register: daytime_stream
  tags:
    - scored
    - section2.1
    - section2.1.2

- name: 2.1.2 Ensure daytime services are not enabled (Disable service) (Scored)
  service: >
      name=daytime-stream
      state=stopped
      enabled=no
  when: daytime_stream.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.2

- name: 2.1.3 Ensure discard services are not enabled (check if exists) (Scored)
  stat: path=/etc/xinetd.d/discard-dgram
  register: discard_dgram
  tags:
    - scored
    - section2.1
    - section2.1.3

- name: 2.1.3 Ensure discard services are not enabled (Disable service) (Scored)
  service: >
      name=discard-dgram
      state=stopped
      enabled=no
  when: discard_dgram.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.3

- name: 2.1.3 Ensure discard services are not enabled (check if exists) (Scored)
  stat: path=/etc/xinetd.d/discard-stream
  register: discard_stream
  tags:
    - scored
    - section2.1
    - section2.1.3

- name: 2.1.3 Ensure discard services are not enabled (Disable service) (Scored)
  service: >
      name=discard-stream
      state=stopped
      enabled=no
  when: discard_stream.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.3

- name: 2.1.4 Ensure echo services are not enabled (check if exists) (Scored)
  stat: path=/etc/xinetd.d/echo-dgram
  register: echo_dgram
  tags:
    - scored
    - section2.1
    - section2.1.4

- name: 2.1.4 Ensure echo services are not enabled (disable xinetd service) (Scored)
  service: >
      name=echo-dgram
      state=stopped
      enabled=no
  when: echo_dgram.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.4

- name: 2.1.4 Ensure echo services are not enabled (check if exists) (Scored)
  stat: path=/etc/xinetd.d/echo-stream
  register: echo_stream
  tags:
    - scored
    - section2.1
    - section2.1.4

- name: 2.1.4 Ensure echo services are not enabled (disable xinetd service) (Scored)
  service: >
      name=echo-stream
      state=stopped
      enabled=no
  when: echo_stream.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.4

- name: 2.1.5 Ensure time services are not enabled (check if exists) (Scored)
  stat: path=/etc/xinetd.d/time-dgram
  register: time_dgram
  tags:
    - scored
    - section2.1
    - section2.1.5

- name: 2.1.5 Ensure time services are not enabled (disable xinetd service) (Scored)
  service: >
      name=time-dgram
      state=stopped
      enabled=no
  when: time_dgram.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.5

- name: 2.1.5 Ensure time services are not enabled (check if exists) (Scored)
  stat: path=/etc/xinetd.d/time-stream
  register: time_stream
  tags:
    - scored
    - section2.1
    - section2.1.5

- name: 2.1.5 Ensure time services are not enabled (disable xinetd service) (Scored)
  service: >
      name=time-stream
      state=stopped
      enabled=no
  when: time_stream.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.5

- name: 2.1.6 (2.2.17 RHEL 7) Ensure rsh server is not enabled (check if exists) (Scored)
  stat: path=/etc/xinetd.d/rsh
  register: rsh
  tags:
    - scored
    - section2.1
    - section2.1.6

- name: 2.1.6 (2.2.17 RHEL 7) Ensure rsh server is not enabled (Disable service)(Scored)
  service: >
    name=rsh
    state=stopped
    enabled=no
  when: rsh.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.6

- name: 2.1.6 (2.2.17 RHEL 7) Ensure rsh server is not enabled (check if exists) (Scored)
  stat: path=/etc/xinetd.d/rexec
  register: rexec
  tags:
    - scored
    - section2.1
    - section2.1.6

- name: 2.1.6 (2.2.17 RHEL 7) Ensure rsh server is not enabled (Disable service)(Scored)
  service: >
    name=rexec
    state=stopped
    enabled=no
  when: rexec.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.6

- name: 2.1.6 (2.2.17 RHEL 7) Ensure rsh server is not enabled (check if exists) (Scored)
  stat: path=/etc/xinetd.d/rlogin
  register: rlogin
  tags:
    - scored
    - section2.1
    - section2.1.6

- name: 2.1.6 (2.2.17 RHEL 7) Ensure rsh server is not enabled (Disable service)(Scored)
  service: >
    name=rlogin
    state=stopped
    enabled=no
  when: rlogin.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.6

- name: 2.1.7 Ensure talk server is not enabled (Scored)
  yum: >
    name=talk
    state=absent
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6") or
        (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
  tags:
    - scored
    - section2.1
    - section2.1.7

- name: 2.1.7 (2.2.18 RHEL 7) Ensure talk server is not enabled (Scored)
  yum: >
    name=talk
    state=absent
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7") or
        (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  tags:
    - scored
    - section2.1
    - section2.1.7

- name: 2.1.8 (2.2.19 RHEL 7) Ensure telnet server is not enabled (Scored)
  yum: >
    name=telnet
    state=absent
  tags:
    - scored
    - section2.1
    - section2.1.8

- name: 2.1.9 (2.2.20 RHEL 7) Ensure tftp server is not enabled (Scored)
  yum: >
    name=tftp
    state=absent
  tags:
    - scored
    - section2.1
    - section2.1.9

- name: 2.1.10 (2.2.21 RHEL 7) Ensure rsync service is not enabled (Scored)
  yum: >
    name=rsync
    state=absent
  tags:
    - scored
    - section2.1
    - section2.1.10

- name: 2.1.11 (2.1.7 RHEL 7) Ensure xinetd is not enabled (check if installed) (Scored)
  stat: path=/etc/init.d/xinetd
  register: xinetd_service
  tags:
    - scored
    - section2.1
    - section2.1.11

- name: 2.1.11 (2.1.7 RHEL 7) Ensure xinetd is not enabled (disable service) (Scored)
  service: >
    name=xinetd
    state=stopped
    enabled=no
  when: xinetd_service.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.11

# Section 2.2 Special Purpose Services

- name: 2.2.1.1 Ensure time synchronization is in use (Not Scored)
  yum: >
    name=ntp
    state=present
  tags:
    - scored
    - section2.2
    - section2.2.1

- name: 2.2.1.2 Ensure ntp is configured (Scored)
  service: >
    name=ntpd
    state=started
    enabled=yes
  tags:
    - scored
    - section2.2
    - section2.2.1.2

- name: 2.2.1.2 Ensure ntp is configured (Scored)
  lineinfile: >
    dest=/etc/sysconfig/ntpd
    regexp=^OPTIONS=
    line=OPTIONS="-u ntp:ntp"
    state=present
  tags:
    - scored
    - section2.2
    - section2.2.1.2

- name: 2.2.1.2 Ensure ntp is configured (Scored)
  lineinfile: >
    dest=/etc/ntp.conf
    state=present
    regexp="^restrict -4 default"
    line="restrict -4 default kod nomodify notrap nopeer noquery"
    insertafter=EOF
  tags:
    - scored
    - section2.2
    - section2.2.1.2

- name: 2.2.1.2 Ensure ntp is configured (Scored)
  lineinfile: >
    dest=/etc/ntp.conf
    state=present
    regexp="^restrict -6 default"
    line="restrict -6 default kod nomodify notrap nopeer noquery"
    insertafter=EOF
  tags:
    - scored
    - section2.2
    - section2.2.1.2

- name: 2.2.1.3 Ensure chrony is configured (Scored)
  debug: msg="*** This recommendation only applies if chrony is in use on the system.*** Evaluate for your environment first."
  tags:
    - scored
    - section2.2
    - section2.2.1.3

- name: 2.2.2 Ensure X Window System is not installed (Scored)
  yum: >
    name=xorg-x11*
    state=absent
  tags:
    - scored
    - section2.2
    - section2.2.2

- name: 2.2.3 Ensure Avahi Server is not enabled (check if installed) (Scored)
  stat: path=/etc/init.d/avahi-daemon
  register: avahi_service
  tags:
    - scored
    - section2.2
    - section2.2.3

- name: 2.2.3 Ensure Avahi Server is not enabled (disable service) (Scored)
  service: >
    name=avahi-daemon
    state=stopped
    enabled=no
  when: avahi_service.stat.exists
  tags:
    - scored
    - section2.2
    - section2.2.3

- name: 2.2.4 Ensure CUPS is not enabled (check if installed) (Scored)
  stat: path=/etc/init.d/cups
  register: cups_service
  tags:
    - scored
    - section2.2
    - section2.2.4

- name: 2.2.4 Ensure CUPS is not enabled (disable service) (Scored)
  service: >
    name=cups
    state=stopped
    enabled=no
  ignore_errors: yes
  when: cups_service.stat.exists
  tags:
    - scored
    - section2.2
    - section2.2.4

- name: 2.2.5 Ensure DHCP Server is not enabled (check if installed) (Scored)
  stat: path=/etc/dhcp.conf
  register: dhcp
  tags:
    - scored
    - section2.2
    - section2.2.5

- name: 2.2.5 Ensure DHCP Server is not enabled (disable service) (Scored)
  service: >
    name=dhcpd
    state=stopped
    enabled=no
  when: dhcp.stat.exists
  tags:
    - scored
    - section2.2
    - section2.2.5

- name: 2.2.6 Ensure LDAP server is not enabled (check if installed) (Scored)
  stat: path=/etc/slapd.conf
  register: slapd
  tags:
    - scored
    - section2.2
    - section2.2.6

- name: 2.2.6 Ensure LDAP server is not enabled (Scored)
  service: >
    name=slapd
    state=stopped
    enabled=no
  when: slapd.stat.exists
  tags:
    - scored
    - section2.2
    - section2.2.6

- name: 2.2.7 Ensure NFS and RPC are not enabled (check for nfs-utils) (Scored)
  stat: path=/etc/init.d/nfslock
  register: nfs_utils
  tags:
    - scored
    - section2.2
    - section2.2.7

- name: 2.2.7 Ensure NFS and RPC are not enabled (check for rpcbind) (Scored)
  stat: path=/etc/init.d/rpcbind
  register: rpcbind
  tags:
    - scored
    - section2.2
    - section2.2.7

- name: 2.2.7 Ensure NFS and RPC are not enabled (Scored)
  service: >
    name=nfs
    state=stopped
    enabled=no
  when: nfs_utils.stat.exists
  tags:
    - scored
    - section2.2
    - section2.2.7

- name: 2.2.7 Ensure NFS and RPC are not enabled (rpcbind services) (Scored)
  service: >
    name=rpcbind
    state=stopped
    enabled=no
  when: rpcbind.stat.exists
  tags:
    - scored
    - section2.2
    - section2.2.7

- name: 2.2.8 Ensure DNS Server is not enabled (check for named.conf) (Scored)
  stat: path=/etc/bind/named.conf
  register: named
  tags:
    - scored
    - section2.2
    - section2.2.8

- name: 2.2.8 Ensure DNS Server is not enabled (Scored)
  service: >
    name=named
    state=stopped
    enabled=no
  when: named.stat.exists
  tags:
    - scored
    - section2.2
    - section2.2.8

- name: 2.2.9 Ensure FTP Server is not enabled (check for vsftpd.conf) (Scored)
  stat: path=/etc/vsftpd/vsftpd.conf
  register: vsftpd
  tags:
    - scored
    - section2.2
    - section2.2.9

- name: 2.2.9 Ensure FTP Server is not enabled (Scored)
  service: >
    name=vsftpd
    state=stopped
    enabled=no
  when: vsftpd.stat.exists
  tags:
    - scored
    - section2.2
    - section2.2.9

- name: 2.2.10 Ensure HTTP server is not enabled (check for httpd) (Scored)
  stat: path=/etc/httpd/conf/httpd.conf
  register: httpd
  tags:
    - scored
    - section2.2
    - section2.2.10

- name: 2.2.10 Ensure HTTP server is not enabled (Scored)
  service: >
    name=httpd
    state=stopped
    enabled=no
  when: httpd.stat.exists
  tags:
    - scored
    - section2.2
    - section2.2.10

- name: 2.2.11 Ensure IMAP and POP3 server is not enabled (check for dovecot) (Scored)
  stat: path=/etc/dovecot/dovecot.conf
  register: dovecot
  tags:
    - scored
    - section2.2
    - section2.2.11

- name: 2.2.11 Ensure IMAP and POP3 server is not enabled (Scored)
  service: >
    name=dovecot
    state=stopped
    enabled=no
  when: dovecot.stat.exists
  tags:
    - scored
    - section2.2
    - section2.2.11

- name: 2.2.11 Ensure IMAP and POP3 server is not enabled (ensure other imap packages are not installed) (Scored)
  yum: >
    name={{ item }}
    state=absent
  with_items:
    - cyrus-imapd
    - cyrus-imapd-devel
    - cyrus-imapd-utils
    - imapfilter
    - imapsync
    - offlineimap
    - php-imap
    - up-imapproxy
    - uw-imap
    - uw-imap-utils

- name: 2.2.12 Ensure Samba is not enabled (Scored)
  yum: >
    name={{ item }}
    state=absent
  with_items:
    - samba
    - samba-client
    - samba-common
  tags:
    - scored
    - section2.2
    - section2.2.12

- name: 2.2.13 Ensure HTTP Proxy Server is not enabled (Scored)
  yum: >
    name=squid
    state=absent
  tags:
    - scored
    - section2.2
    - section2.2.13

- name: 2.2.14 Ensure SNMP Server is not enabled (Scored)
  yum: >
    name={{ item }}
    state=absent
  with_items:
    - net-snmp
    - net-snmp-utils
  tags:
    - scored
    - section2.2
    - section2.2.14

- name: 2.2.15 Ensure mail transfer agent is configured for local-only mode (Scored)
  lineinfile: >
    backup=yes
    state=present
    dest=/etc/postfix/main.cf
    backrefs=yes
    regexp="^inet_interfaces"
    line="inet_interfaces = localhost"
  ignore_errors: yes
  tags:
    - scored
    - section2.2
    - section2.2.15

- name: 2.2.16 Ensure NIS Server is not enabled (Scored)
  yum: >
    name=ypserv
    state=absent
  tags:
    - scored
    - section2.2
    - section2.2.16

# Section 2.3 Service Clients

- name: 2.3.1 Ensure NIS Client is not installed (Scored)
  yum: >
    name=ypbind
    state=absent
  tags:
    - scored
    - section2.3
    - section2.3.1

- name: 2.3.2 Ensure rsh client is not installed (Scored)
  yum: >
    name=rsh
    state=absent
  tags:
    - scored
    - section2.3
    - section2.3.2

- name: 2.3.3 Ensure talk client is not installed (Scored)
  yum: >
    name=talk
    state=absent
  tags:
    - scored
    - section2.3
    - section2.3.3

- name: 2.3.4 Ensure telnet client is not installed (Scored)
  yum: >
    name=telnet
    state=absent
  tags:
    - scored
    - section2.3
    - section2.3.4

- name: 2.3.5 Ensure LDAP client is not installed (Scored)
  yum: >
    name=openldap-clients
    state=absent
  tags:
    - scored
    - section2.3
    - section2.3.5
