---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#   Section 4.2 Configure Logging
#
  - name: 4.2.1.1 Ensure rsyslog Service is enabled (Scored)
    yum: >
      name=rsyslog
      state=present
    tags:
      - scored
      - section4.2
      - section4.2.1
      - section4.2.1.1

  - name: 4.2.1.1 Ensure rsyslog Service is enabled (Scored)
    service: >
      name=rsyslog
      enabled=yes
      state=started
    tags:
      - scored
      - section4.2
      - section4.2.1
      - section4.2.1.1

  - name: 4.2.1.2 Ensure logging is configured (Not Scored) #comment: rsyslog.conf needs to be edited to match the updated CIS recommendations.
    copy: >
      src=etc/rsyslog.conf
      dest=/etc/rsyslog.conf
      owner=root
      group=root
      mode=0644
    tags:
      - notscored
      - section4.2
      - section4.2.1
      - section4.2.1.2

  - name: 4.2.1.3 Ensure rsyslog default file permissions configured (Scored) #comment: this needs to be reviewed by a savvy linux guru.
    file: >
      path=/var/log/{{ item }}
      state=touch
      owner=root
      group=wheel
      mode=0640
    with_items:
        - messages
        - kern.log
        - daemon.log
        - syslog
        - unused.log
    tags:
      - scored
      - section4.2
      - section4.2.1
      - section4.2.1.3

  - name: 4.2.1.4 Ensure rsyslog is configured to send logs to a remote log host (Scored) #comment: needs to be checked for value of rsyslog_dest. This should be the target log server??
    lineinfile: >
      state=present
      dest=/etc/rsyslog.conf
      regexp="^\*\.\*"
      line="*.* @@{{ rsyslog_dest }}"
    when: rsyslog_dest is defined
    tags:
      - scored
      - section4.2
      - section4.2.1
      - section4.2.1.4

  - name: 4.2.1.5 Ensure remote rsyslog messages are only accepted on designated log hosts. (Not Scored)
    lineinfile: >
      state=present
      line="$ModLoad imtcp.so"
    when: rsyslog_host
    tags:
      - notscored
      - section4.2
      - section4.2.1
      - section4.2.1.5

  - name: 4.2.1.5 Ensure remote rsyslog messages are only accepted on designated log hosts. (Not Scored)
    lineinfile: >
      state=present
      line="$InputTCPServerRun 514"
    when: rsyslog_host
    tags:
      - notscored
      - section4.2
      - section4.2.1
      - section4.2.1.5

#comment: Need to build out controls 4.2.2.1 through 4.2.4

  - name: 4.2.3 Ensure rsyslog or syslog-ng is installed (Scored)
    yum: >
      name=rsyslog
      state=present
    tags:
      - scored
      - section4.2
      - section4.2.3

  - name: 4.3 Ensure logrotate is configured (Not Scored)
    copy: >
      src=etc/logrotate.d/syslog
      dest=/etc/logrotate.d/syslog
    tags:
      - notscored
      - section4.3
