---
#
# Copyright 2016 VVL Systems & Consulting
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#   This section addresses configuration settings that should be addressed
#   during initial setup of the operating system.
#
#   Section 1.1 Filesystem Configuration

# TODO: move this first task to section 1.2 to fix failure on first run or new server

  - name: Create /etc/modprobe.d/CIS.conf with root ownership & mode
    file: path=/etc/modprobe.d/CIS.conf state=touch owner=root group=root mode=0600
    changed_when: false
    tags:
      - notscored
      - section1.1
      - section1.1.18
      - section1.1.19
      - section1.1.20
      - section1.1.21
      - section1.1.22
      - section1.1.23
      - section1.1.24

  - name: 1.1.2 Ensure separate partition exists for /tmp (Scored)
    debug: msg="*** Manually create Separate Partition for /tmp."
    tags:
      - scored
      - section1.1
      - section1.1.2

  - name: 1.1.6 Ensure separate partition exists for /var (Scored)
    debug: msg="*** Manually create Separate Partition for /var."
    tags:
      - scored
      - section1.1
      - section1.1.6

  - name: 1.1.7 Ensure separate partition exists for /var/tmp (Scored)
    debug: msg="*** Manually create Separate Partition for /var/tmp."
    tags:
      - scored
      - section1.1
      - section1.1.7

  - name: 1.1.11 Ensure separate partition exists for /var/log (Scored)
    debug: msg="*** Manually create Separate Partition for /var/log."
    tags:
      - scored
      - section1.1
      - section1.1.11

  - name: 1.1.12 Ensure separate partition exists for /var/log/audit (Scored)
    debug: msg="*** Manually create Separate Partition for /var/log/audit."
    tags:
      - scored
      - section1.1
      - section1.1.12

  - name: 1.1.13 Ensure separate partition exists for /home (Scored)
    debug: msg="*** Manually create Separate Partition for /home."
    tags:
      - scored
      - section1.1
      - section1.1.13

# Section 1.2 Configure Software Updates

  - name: 1.2.5 Disable the rhnsd Daemon (Not Scored)
    action: command /sbin/chkconfig rhnsd off
    when: ansible_distribution == "RedHat"
    tags:
      - notscored
      - section1.2
      - section1.2.5

#   Section 1.6 Mandatory Access Control

  - name: 1.6.1.1 Ensure SELinux is not disabled in bootloader configuration (Scored)
    lineinfile: >
      state=absent
      dest=/etc/grub.conf
      line="selinux=0"
    tags:
      - scored
      - section1.6
      - section1.6.1.1

  - name: 1.6.1.1 Ensure SELinux is not disabled in bootloader configuration (Scored)
    lineinfile: >
      state=absent
      dest=/etc/grub.conf
      line="enforcing=0"
    tags:
      - scored
      - section1.6
      - section1.6.1.1

  - name: 1.6.1.2 to 1.6.1.3 Ensure SELinux state and policy are configured (Scored)
    selinux: >
      state=enforcing
      policy=targeted
    ignore_errors: yes
    tags:
      - scored
      - section1.6
      - section1.6.1
      - section1.6.1.2
      - section1.6.1.3

  - name: 1.6.1.4 Ensure SETroubleshoot is not installed (Scored)
    yum: >
      name=setroubleshoot
      state=absent
    tags:
      - scored
      - section1.6
      - section1.6.1.4

  - name: 1.6.1.5 Ensure the MCS Translation Service (mcstrans) is not installed (Scored)
    yum: >
      name=mcstrans
      state=absent
    tags:
      - scored
      - section1.6
      - section1.6.1.5

  - name: 1.6.1.6 Ensure no unconfined daemons exist (Scored)
    debug: msg="*** Check via cron jobs or manually."
    tags:
      - scored
      - section1.6
      - section1.6.1.6

  - name: 1.6.2 Ensure SELinux is installed (Scored)
    yum: >
      name=libselinux
      state=present
    tags:
      - scored
      - section1.6
      - section1.6.2
