---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: 1.1.2 Ensure separate partition exists for /tmp (Scored)
    debug: msg="*** Manually create Separate Partition for /tmp."
    tags:
      - scored
      - section1.1
      - section1.1.2

  - name: 1.1.3 - 1.1.5 Ensure nodev,nosuid,noexec option set for /tmp Partition (Scored)
    mount: >
      name="/tmp"
      src={{ item.device }}
      state=mounted
      fstype={{ item.fstype }}
      opts="nodev,nosuid,noexec"
    when: item.mount == "/tmp"
    with_items: ansible_mounts
    tags:
      - scored
      - section1.1
      - section1.1.3
      - section1.1.4
      - section1.1.5

  - name: 1.1.6 Ensure separate partition exists for /var (Scored)
    debug: msg="*** Manually create Separate Partition for /var."
    tags:
      - scored
      - section1.1
      - section1.1.6

  - name: 1.1.7 Ensure separate partition exists for /var/tmp (Scored)
    debug: msg="*** Manually create Separate Partition for /var/tmp."
    tags:
      - scored
      - section1.1
      - section1.1.7

  - name: 1.1.8 - 1.1.10 Ensure nodev,nosuid,noexec option set for /var/tmp Partition (Scored)
    mount: >
      name="/var/tmp"
      src={{ item.device }}
      state=mounted
      fstype={{ item.fstype }}
      opts="nodev,nosuid,noexec"
    when: item.mount == "/var/tmp"
    with_items: ansible_mounts
    tags:
      - scored
      - section1.1
      - section1.1.8
      - section1.1.9
      - section1.1.10

  - name: 1.1.11 Ensure separate partition exists for /var/log (Scored)
    debug: msg="*** Manually create Separate Partition for /var/log."
    tags:
      - scored
      - section1.1
      - section1.1.11

  - name: 1.1.12 Ensure separate partition exists for /var/log/audit (Scored)
    debug: msg="*** Manually create Separate Partition for /var/log/audit."
    tags:
      - scored
      - section1.1
      - section1.1.12

  - name: 1.1.13 Ensure separate partition exists for /home (Scored)
    debug: msg="*** Manually create Separate Partition for /home."
    tags:
      - scored
      - section1.1
      - section1.1.13

  - name: 1.1.14 Ensure nodev option set on /home partition (Scored)
    mount: >
      name="/home"
      src={{ item.device }}
      state=mounted
      fstype={{ item.fstype }}
      opts="nodev"
    when: item.mount == "/home"
    with_items: ansible_mounts
    tags:
      - scored
      - section1.1
      - section1.1.14

  - name: 1.1.15 - 1.1.17 Ensure nodev, nosuid, noexec option set on /dev/shm Partition (Scored)
    mount: >
      name="/dev/shm"
      src="none"
      state=mounted
      fstype="tmpfs"
      opts="nodev,nosuid,noexec"
    tags:
      - section1.1
      - section1.1.15
      - section1.1.16
      - section1.1.17
      - scored

  - name: 1.1.18 Ensure nodev option set on removable media partitions (Not Scored)
    debug: msg="*** Not relevant."
    tags:
      - scored
      - section1.1
      - section1.1.18

  - name: 1.1.19 Ensure nosuid option set on removable media partitions (Not Scored)
    debug: msg="*** Not relevant."
    tags:
      - notscored
      - section1.1
      - section1.1.19

  - name: 1.1.20 Ensure noexec option set on removable media partitions (Not Scored)
    debug: msg="*** Not relevant."
    tags:
      - notscored
      - section1.1
      - section1.1.20


  - name: 1.1.21 Ensure sticky bit is set on all world-writable directories (Scored)
    debug: msg="*** May be too destructive -- see notes"
    tags:
      - scored
      - section1.1
      - section1.1.21

  - name: 1.1.22 Disable Automounting (Scored)
    debug: msg="*** May be too destructive -- see notes"
    tags:
      - scored
      - section1.1
      - section1.1.22

  - name: 1.2.1 Ensure package manager repositories are configured (Not Scored)
    command: yum check-update
    register: result
    failed_when: "result.rc == 1"
    when: ansible_distribution == "RedHat"
    tags:
      - notscored
      - section1.2
      - section1.2.1

  - name: 1.2.2 Ensure gpgcheck is globally activated (Scored)
    lineinfile: >
      state=present
      dest=/etc/yum.conf 
      #comment need to add /etc/yum.repos.d/*
      regexp=^gpgcheck=
      line=gpgcheck=1
    tags:
      - scored
      - section1.2
      - section1.2.2

  - name: 1.2.3 Ensure GPG keys are configured (Not Scored)
    command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release 
    when: ansible_distribution == "RedHat"
    tags:
      - scored
      - section1.2
      - section1.2.3

  - name: 1.2.4 Ensure Red Hat Network or Subscription Manager connection is configured (Not Scored)
    debug: msg="*** Check manually."
    tags:
      - notscored
      - section1.2
      - section1.2.4

  - name: 1.2.6 Verify package integrity using RPM (Not Scored)
    debug: msg="*** Check via cron/AIDE/manually"
    tags:
      - notscored
      - section1.2
      - section1.2.6

  - name: 1.5.1 Get Absolute Path to grub.conf
    command: readlink -f /etc/grub.conf
    register: readlink
    changed_when: false
    always_run: yes
    tags:
      - scored
      - section1.5
      - section1.5.1

  - name: 1.5.1 Set User/Group Owner on /etc/grub.conf (Scored)
    file: >
      path={{ readlink.stdout }}
      owner=root
      group=root
    tags:
      - scored
      - section1.5
      - section1.5.1

  - name: 1.5.2 Get Absolute Path to grub.conf
    command: readlink -f /etc/grub.conf
    register: readlink
    changed_when: false
    always_run: yes
    tags:
      - scored
      - section1.5
      - section1.5.2

  - name: 1.5.2 Set Permissions on /etc/grub.conf (Scored)
    file: >
      path={{ readlink.stdout }}
      mode=0400
    tags:
      - scored 
      - section1.5
      - section1.5.2

  - name: 1.4.2 Ensure bootloader password is set (Scored)
    debug: msg="*** Too destructive for production systems. Evaluate for your environment first."
    tags:
      - scored
      - section1.4
      - section1.4.2

  - name: 1.4.3 Ensure authentication required for single user mode (Scored)
    debug: msg="*** Too destructive for production systems. Evaluate for your environment first."
    tags:
      - scored
      - section1.4
      - section1.4.3

  - name: 1.4.4 Ensure interactive boot is not enabled (Scored)
    lineinfile: >
      dest=/etc/sysconfig/init
      regexp=^PROMPT=
      line=PROMPT=no
    tags:
      - scored
      - section1.4
      - section1.4.4

  - name: 1.5.1 Ensure core dumps are restricted (Scored)
    lineinfile: >
      dest=/etc/security/limits.conf
      line="* hard core 0"
      insertafter=EOF
    tags:
      - scored
      - section1.5
      - section1.5.1

  - name: 1.5.1 Ensure core dumps are restricted (Scored) - via sysctl
    sysctl: >
      name=fs.suid_dumpable
      value=0
      state=present
      ignoreerrors=yes
    tags:
      - scored
      - section1.5
      - section1.5.1

  - name: 1.6.2 Configure ExecShield (Scored)
    sysctl: >
      name=kernel.exec-shield
      value=1
      state=present
      ignoreerrors=yes
    tags:
      - scored
      - section1.6
      - section1.6.2

  - name: 1.5.3 Ensure address space layout randomization (ASLR) is enabled (Scored)
    sysctl: >
      name=kernel.randomize_va_space
      value=2
      state=present
      ignoreerrors=yes
    tags:
      - scored
      - section1.5
      - section1.5.3

  - name: 1.7 Use the Latest OS Release (Not Scored)
    command: >
      cat /etc/redhat-release
    when: ansible_distribution == "RedHat"
    tags:
      - notscored
      - section1.7

  - name: 1.7.1.1 Ensure message of the day is configured properly (Scored)
    

    tags:
      - scored
      - section1.7
      - section1.7.1.1

  - name: 1.7.1.2 Ensure local login warning banner is configured properly (Not Scored)
    

    tags:
      - scored
      - section1.7
      - section1.7.1.2

  - name: 1.7.1.3 Ensure remote login warning banner is configured properly (Not Scored)
    

    tags:
      - scored
      - section1.7
      - section1.7.1.3

  - name: 1.7.1.4 Ensure permissions on /etc/motd are configured (Not Scored)
    

    tags:
      - scored
      - section1.7
      - section1.7.1.4

  - name: 1.7.1.5 Ensure permissions on /etc/issue are configured (Scored)
    

    tags:
      - scored
      - section1.7
      - section1.7.1.5

  - name: 1.7.1.6 Ensure permissions on /etc/issue.net are configured (Not Scored)
    

    tags:
      - scored
      - section1.7
      - section1.7.1.6

  - name: 1.7.2 Ensure GDM login banner is configured (Scored)
    

    tags:
      - scored
      - section1.7
      - section1.7.2

  - name: 1.8 Ensure updates, patches, and additional security software are installed (Not Scored)
    

    tags:
      - scored
      - section1.8